name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Set up environment variables
        run: |
          echo "MYSQLUSER=${{ secrets.MYSQLUSER }}" >> $GITHUB_ENV
          echo "MYSQLPASSWORD=${{ secrets.MYSQLPASSWORD }}" >> $GITHUB_ENV
          echo "MYSQLDATABASE=${{ secrets.MYSQLDATABASE }}" >> $GITHUB_ENV
          echo "MYSQLHOST=${{ secrets.MYSQLHOST }}" >> $GITHUB_ENV
          echo "MYSQLPORT=${{ secrets.MYSQLPORT }}" >> $GITHUB_ENV
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "SPRING_MAIL_PORT=${{ secrets.SPRING_MAIL_PORT }}" >> $GITHUB_ENV
          echo "SPRING_MAIL_USERNAME=${{ secrets.SPRING_MAIL_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_MAIL_PASSWORD=${{ secrets.SPRING_MAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
